accounts/urls.py
from django.urls import path
from accounts import views


urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('create_account/', views.create_account, name='create_account'),
]

bandfollow/urls.py
from django.contrib import admin
from django.urls import path, include

from bands import views as bands_views
from accounts import views as accounts_views


urlpatterns = [
    path('', bands_views.home_page, name='home'),
    path('artists/', bands_views.artists, name='artists'),
    path('artists/<str:name>', bands_views.artist_detail, name='artist_detail'),
    path('add_artist/', bands_views.add_artist, name='add_artist'),
    path('set_favorite_artist/', bands_views.set_favorite_artist, name='set_favorite_artist'),
    path('venues/', bands_views.venues, name='venues'),
    path('venues/<str:name>', bands_views.venue_detail, name='venue_detail'),
    path('add_venue/', bands_views.add_venue, name='add_venue'),
    path('events/', bands_views.events, name='events'),
    path('event_detail/<int:id>', bands_views.event_detail, name='event_detail'),
    path('set_favorite_venue/', bands_views.set_favorite_venue, name='set_favorite_venue'),
    path('add_event/', bands_views.add_event, name='add_event'),
    path('about/', bands_views.about, name='about'),
    path('admin/', admin.site.urls),
    path('create_account/', accounts_views.create_account, name='create_account'),
    path('search/', bands_views.search, name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('approve_artists/', bands_views.approve_artists, name='approve_artists'),
    path('activate/<uidb64>/<token>', accounts_views.activate, name='activate'),
]

bands/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class user(abstractuser):

    username = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    is_moderator = models.BooleanField(default=False)
    favorite_artists = models.ManyToManyField('Artist', blank=True)
    favorite_venues = models.ManyToManyField('Venue', blank=True)

    USERNAME_FIELD = 'username'


class Artist(models.Model):

    name = models.CharField(max_length=200)
    is_approved = models.BooleanField(default=False)
    website = models.URLField(blank=True)

    def get_absolute_url(self):
        return reverse('artist_detail', args=[str(self.name)])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'artist'
        verbose_name_plural = 'artists'


class Venue(models.Model):

    name = models.CharField(max_length=200)
    is_approved = models.BooleanField(default=False)
    website = models.URLField(blank=True)

    def get_absolute_url(self):
        return reverse('venue_detail', args=[str(self.name)])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'venue'
        verbose_name_plural = 'venues'


class Event(models.Model):

    title = models.CharField(max_length=200)
    date_and_time = models.DateTimeField()
    is_approved = models.BooleanField(default=False)
    artists = models.ManyToManyField('Artist')
    venue = models.ForeignKey('Venue', on_delete=models.PROTECT)

    @property
    def artist_list(self):
        return ','.join([artist.name for artist in self.artists.all()])

    def get_absolute_url(self):
        return reverse('event_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.date_and_time}: {self.title}'

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'events'


class Alert(models.Model):

    event = models.ForeignKey('Event', on_delete=models.PROTECT, blank=True)
    user = models.ForeignKey('User', on_delete=models.PROTECT, blank=True)
    has_been_sent = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.event.title} - {self.user.username}'

bands/forms.py
from django import forms
from django.urls import reverse
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper

from bands.models import Artist, Venue, Event


class ArtistCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id_add_artist_form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('add_artist')
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Artist
        fields = ['name', 'website']


class VenueCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id_add_venue_form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('add_venue')
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Venue
        fields = ['name', 'website']


class EventCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id_add_event_form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('add_event')
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Event
        fields = ['title', 'date_and_time', 'venue', 'artists']

bands/views.py
from datetime import datetime
from itertools import chain

from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db import models

from bands.forms import ArtistCreationForm, VenueCreationForm, EventCreationForm
from bands.models import Artist, Venue, Event


def home_page(request):
    return render(request, 'bands/index.html')


def artists(request):
    approved_artists = Artist.objects.filter(is_approved=True).order_by('name')
    return render(request, 'bands/artists.html', {'artists': approved_artists})


def artist_detail(request, name):
    artist = get_object_or_404(Artist, name=name)
    upcoming_events = Event.objects.filter(artists__event__artists=artist, date_and_time__gte=timezone.now()).distinct()

    print(upcoming_events)

    return render(request, 'bands/artist_detail.html', {'artist': artist, 'events': upcoming_events})


def about(request):
    return render(request, 'bands/about.html')


@login_required
def add_artist(request):
    if request.method == 'POST':
        new_artist_form = ArtistCreationForm(data=request.POST)
        if new_artist_form.is_valid():
            new_artist_form.save()
            return redirect(artists)
        else:
            return render(request, 'bands/add_artist.html', {'form': new_artist_form})
    return render(request, 'bands/add_artist.html', {'form': ArtistCreationForm()})


@login_required
def set_favorite_artist(request):
    if request.method == 'POST':
        user = request.user
        artist = Artist.objects.get(id=request.POST.get('artist_id'))
        if request.POST.get('is_favorite') == 'true':
            user.favorite_artists.add(artist)
        else:
            user.favorite_artists.remove(artist)

        return redirect(artist)
    return redirect('home')


@login_required
def approve_artists(request):
    user = request.user
    if not user.is_moderator:
        return render(request, 'bands/access_denied.html')

    unapproved_artists = Artist.objects.filter(is_approved=False)

    return render(request, 'bands/approve_artists.html', {'unapproved_artists': unapproved_artists})


def venues(request):
    approved_venues = Venue.objects.filter(is_approved=True).order_by('name')
    return render(request, 'bands/venues.html', {'venues': approved_venues})


def venue_detail(request, name):
    venue = get_object_or_404(Venue, name=name)
    upcoming_events = Event.objects.filter(venue=venue, date_and_time__gte=timezone.now())

    return render(request, 'bands/venue_detail.html', {'venue': venue, 'events': upcoming_events})


@login_required
def set_favorite_venue(request):
    if request.method == 'POST':
        user = request.user
        venue = Venue.objects.get(id=request.POST.get('venue_id'))
        if request.POST.get('is_favorite') == 'true':
            user.favorite_venues.add(venue)
        else:
            user.favorite_venues.remove(venue)

        return redirect(venue)
    return redirect('home')


@login_required
def add_venue(request):
    if request.method == 'POST':
        new_venue_form = VenueCreationForm(data=request.POST)
        if new_venue_form.is_valid():
            new_venue_form.save()
            return redirect(venues)
        else:
            return render(request, 'bands/add_venue.html', {'form': new_venue_form})
    return render(request, 'bands/add_venue.html', {'form': VenueCreationForm()})


def events(request):
    approved_events = Event.objects.filter(is_approved=True, date_and_time__gte=datetime.today())
    return render(request, 'bands/events.html', {'events': approved_events})


def event_detail(request, id):
    event = get_object_or_404(Event, id=id)
    return render(request, 'bands/event_detail.html', {'event': event})


@login_required
def add_event(request):
    if request.method == 'POST':
        new_event_form = EventCreationForm(data=request.POST)
        if new_event_form.is_valid():
            new_event_form.save()
            return redirect(events)
        else:
            return render(request, 'bands/add_event.html', {'form': new_event_form})

    return render(request, 'bands/add_event.html', {'form': EventCreationForm()})


def search(request):
    search_query = request.GET.get('search_query')

    artists = Artist.objects.filter(name__icontains=search_query)
    venues = Venue.objects.filter(name__icontains=search_query)
    events = Event.objects.filter(title__icontains=search_query)

    if len(artists) + len(venues) + len(events) > 0:
        results_found = True
    else:
        results_found = False

    return render(request, 'bands/search.html', {'artists': artists, 'venues': venues, 'events': events,
                                                 'results_found': results_found})

bands/templates/bands/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}


<!-- About Section -->

   <!-- Wrap the rest of the page in another container to center all the content. -->
    <div class="container marketing">
      <!-- Three columns of text below the carousel -->

      <!-- START THE FEATURETTES -->
      <hr class="featurette-divider">
      <div class="row featurette">
          <h2 class="featurette-heading">Why we built this website?</h2>
          <p class="lead">Our story begins in Doha, Qatar. We are expat professionals who love music and tend to miss live music events of our favorite artists, venues and events.</p>
      </div>
      <hr class="featurette-divider">
      <div class="row featurette">
          <h2 class="featurette-heading">What services do we provide?</h2>
          <p class="lead">BandFollow is a free service offering notification of live music events near you via a subscription model. Mobile-friendly and simple user interface, this site provides the user the ability to add artists, venues and events manually. Once it is approved by an admin, any BandFollow member can subscribe for notification.</p>
      </div>
      <hr class="featurette-divider">
      <div class="row featurette">
          <h2 class="featurette-heading">Who are we?</h2>
          <p class="lead">We are a group of Northwestern School of Professional Studies (SPS) graduate students working to earn more than an "A" on our Capstone project.</p>
      </div>
      <div class="row">
        <div class="col-lg-3  ">
          <img class="img-circle rounded-circle border" src="https://www.qatar.northwestern.edu/images/people/mctigue-tames.jpg" alt="McTiguer" width="110" height="160">
          <h5 >Tames McTigue</h5>
          <h6 >Lead Backend Developer</h6>
          <p>aka McTiguer</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle rounded-circle border" src="https://www.qatar.northwestern.edu/images/people/ravishankar-rajiv.jpg" alt="Raj-Mahal" width="110" height="160">
          <h5 >Rajiv Ravishankar</h5>
          <h6 >Lead Frontend Developer</h6>
          <p>aka Raj Mahal</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle rounded-circle border" src="https://www.qatar.northwestern.edu/images/people/bowman-lea.jpg" alt="lea" width="110" height="160">
          <h5 >lea bowman</h5>
          <h6 >Lead Database Admin</h6>
          <p>aka bow-manager</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle rounded-circle border" src="https://www.qatar.northwestern.edu/images/people/sotelo-alex.jpg" alt="Juan-Solo" width="110" height="160">
          <h5 >Alex Sotelo</h5>
          <h6 >Project Manager</h6>
          <p>aka Juan Solo</p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
      <hr class="featurette-divider">
      <!-- /END THE FEATURETTES -->
    </div><!-- /.container -->
{% endblock %}

bands/templates/bands/access_denied.html
{% extends 'base.html' %}
{% block title %}BandFollow - Access Denied{% endblock %}

{% block content %}
    <h2>Sorry, you do not have access to this page.</h2>
{% endblock %}

bands/templates/bands/add_artist.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}BandFollow - Add an Artist{% endblock %}

{% block content %}
    <div class="container">
        {% crispy form %}
    </div>
{% endblock %}

bands/templates/bands/add_event.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}BandFollow - Add an Event{% endblock %}
{% block extra_head_tags %}
    <link rel="stylesheet" href="{% static 'css/flatpickr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/multi-select.dist.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
    {% crispy form %}
    </div>
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'js/flatpickr.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.multi-select.js' %}"></script>
    <script type="text/javascript">
        flatpickr("#id_date_and_time", {enableTime: true, minDate: "today"});
        $('#id_artists').multiSelect();
    </script>
{% endblock %}

bands/templates/bands/add_venue.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}BandFollow - Add a Venue{% endblock %}

{% block content %}
    <div class="container">
    {% crispy form %}
    </div>
{% endblock %}

bands/templates/bands/approve_artists.html
{% extends 'base.html' %}

{% block title %}BandFollow - Approve Artists{% endblock %}

{% block content %}
    <h2>Unapproved Artists</h2>

    {% if unapproved_artists %}
    <ul>
    {% for artist in unapproved_artists %}
        <li><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <h3>There are currently no artists to approve. Please check again later.</h3>
    {% endif %}
{% endblock %}

bands/templates/bands/artists.html
{% extends 'base.html' %}

{% block title %}BandFollow - Artists{% endblock %}

{% block content %}

    <p><a href="{% url 'add_artist' %}" id="id_add_artist">
        <button id="id_add_artist" class="btn btn-primary" type="button">Add a New Artist...</button>
    </a></p>
    <h2>Artist List</h2>
    <table id="id_list_table">
        <thead>
        <tr>
            <th>Artist Name</th>
        </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td><a href="{{ artist.get_absolute_url }}" id="id_artist_name">{{ artist.name }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

bands/templates/bands/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'bootstrap/css/custom.css' %}">



    <title>{% block title %}BandFollow{% endblock %}</title>

</head>
<body>

    <div class="page-header">
        <h1><a href="/index">BandFollow</a></h1>
    </div>

    <div class="navbar-wrapper">
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/index">Home</a></li>
                <li><a href="/about">About</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/login">Login</a></li>
                    <li><a href="/create_account">Sign Up</a></li>
                    <li><a href="#">Moderator</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">More</li>
                    <li><a href="#">Suggestions?</a></li>
                    <li><a href="#">Contact Us</a></li>
                  </ul>
                </li>
              </ul>
        </nav>

      </div>
    </div>
{% block content %}

{% endblock %}
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

bands/templates/bands/event_detail.html
{% extends 'base.html' %}

{% block title %}BandFollow - {{ event.title }}{% endblock %}

{% block content %}
    <div class="container">
        <p><a href="{% url 'events' %}" id="id_event_list">Go back to event list</a></p>
    <h1>{{ event.title }}</h1>
    </div>
    <div class="container">
    <table class="table">
        <tr>
            <th>Venue</th>
            <td><a href="{{ event.venue.get_absolute_url }}">{{ event.venue }}</a></td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ event.date_and_time }}</td>
        </tr>
        <tr>
            <th>Artists</th>
            {% for artist in event.artists.all %}
                <td><a href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></td>
            {% endfor %}
        </tr>
    </table>
    </div>
{% endblock %}

bands/templates/bands/events.html
{% extends 'base.html' %}

{% block title %}BandFollow - Events{% endblock %}

{% block content %}
    <div class="container">
        <p><a href="{% url 'add_event' %}" id="id_add_venue">
            <button class="btn btn-primary" type="button">Add a New Event...</button>
        </a></p>
        <table id="id_list_table" class="table">
            <thead>
            <tr>
                <th scope="col">Event Name</th>
                <th scope="col">Event Location</th>
                <th scope="col">Date</th>
                <th scope="col">Artists</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></td>
                    <td>{{ event.venue.name }}</td>
                    <td>{{ event.date_and_time|date:'F j, Y' }}</td>
                    <td>{{ event.artist_list }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

bands/templates/bands/login.html
{% extends 'bands/base.html' %}

{% block title %}Login{% endblock %}
{% block content %}
    <form method="post" action="{% url 'login' %}">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Login" id="id_submit">
    </form>
{% endblock %}

bands/templates/bands/search.html
{% extends 'base.html' %}
{% block title %}BandFollow - Search{% endblock %}
{% block content %}

    <h1>Search Results</h1>

    {% if results_found %}

    {% if artists %}
    <h2>Artists</h2>
    <ul>
    {% for artist in artists %}
        <li><a  href="{{ artist.get_absolute_url }}">{{ artist.name }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
    {% if venues %}
    <h2>Venues</h2>
    <ul>
    {% for venue in venues %}
        <li><a  href="{{ venue.get_absolute_url }}">{{ venue.name }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
    {% if events %}
    <h2>Events</h2>
    <ul>
    {% for event in events %}
        <li><a  href="{{ event.get_absolute_url }}">{{ event.title }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}

    {% else %}
        <h2>Sorry, no results were found.</h2>
    {% endif %}
{% endblock %}

bands/templates/bands/venue_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}BandFollow - {{ venue.name }} {% endblock %}

{% block content %}
    <div class="container">
        <p><a href="{% url 'venues' %}" id="id_artist_list">Go back to venue list</a></p>

        <div class="row">
            <div class="col"><h1>{{ venue.name }}</h1></div>
            <div class="col">
                <form id="id_set_favorite" action="{% url 'set_favorite_venue' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ venue.id }}" name="venue_id">
                    {% if venue in user.favorite_venues.all %}
                        <input type="hidden" value="false" name="is_favorite">
                        <button class="btn btn-primary" type="submit">Remove from Favorite Venues</button>
                    {% else %}
                        <input type="hidden" value="true" name="is_favorite">
                        <button class="btn btn-primary" type="submit">Add to Favorite Venues</button>
                    {% endif %}
                </form>
            </div>
        </div>

        {% if venue.website %}
            <p>Website: <a href="{{ venue.website }}" target="_blank">{{ venue.website }}</a></p>
        {% endif %}

        <div class="container">
            <h2>Upcoming Events</h2>
            <table id="id_event_table" class="table">
                <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Date</th>
                    <th scope="col">Artists</th>
                </tr>
                </thead>
                <tbody>
                {% for event in events %}
                    <tr>
                        <td><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></td>
                        <td>{{ event.date_and_time }}</td>
                        <td>{{ event.artist_list }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

bands/templates/bands/venues.html
{% extends 'base.html' %}

{% block title %}BandFollow - Venues{% endblock %}

{% block content %}
    <p><a href="{% url 'add_venue' %}" id="id_add_venue">
        <button class="btn btn-primary" type="button">Add a New Venue...</button>
    </a></p>
<table id="id_list_table">
<thead>
    <tr>
        <th>Venue Name</th>
    </tr>
</thead>
<tbody>
{% for venue in venues %}
    <tr>
        <td><a href="{{ venue.get_absolute_url }}" id="id_venue_name">{{ venue.name }}</a></td>
    </tr>
{% endfor %}
</tbody>
</table>
{% endblock %}